import { useCallback, useEffect, useRef, useState } from 'react';
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, LinearProgress, MenuItem, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import { apiClient } from '@/shared/api/axios';
import { apiErrorMessage } from '@/shared/api/error';
import ChatSearch from './ChatSearch';
import type { Participant } from '../api';
type Note={content:string;version:number;author:string|null;updatedAt:string|null};
type Task={id:number;title:string;description:string|null;assigneeId:number|null;assignee:string|null;dueDate:string|null;status:'TODO'|'DOING'|'DONE';revision:number};
type Poll={id:number;question:string;closed:boolean;myVote:number|null;options:{id:number;label:string;count:number}[]};
type Mark={id:number;label:string;atMs:number;authorId:number;author:string};
type Summary={note:Note;tasks:Task[];polls:Poll[];bookmarks:Mark[]};
const emptyTask={title:'',description:'',assigneeId:'',dueDate:'',status:'TODO' as Task['status']};
export default function MeetingTools({open,onClose,roomId,me,participants}:{open:boolean;onClose:()=>void;roomId:string;me:Participant;participants:Participant[]}){
 const base=`/room/${roomId}/meeting`,[tab,setTab]=useState(0),[data,setData]=useState<Summary|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [draft,setDraft]=useState(''),[version,setVersion]=useState(0),[dirty,setDirty]=useState(false);const dirtyRef=useRef(false);dirtyRef.current=dirty;
 const [task,setTask]=useState(emptyTask),[editing,setEditing]=useState<Task|null>(null),[question,setQuestion]=useState(''),[options,setOptions]=useState('찬성\n반대'),[label,setLabel]=useState('');
 const mounted=useRef(true),generation=useRef(0);const elevated=me.role!=='MEMBER';
 useEffect(()=>()=>{mounted.current=false;generation.current++;},[]);
 const load=useCallback(async()=>{const g=++generation.current;const {data:d}=await apiClient.get<Summary>(base);if(!mounted.current||g!==generation.current)return;setData(d);if(!dirtyRef.current){setDraft(d.note.content);setVersion(d.note.version);}return d;},[base]);
 useEffect(()=>{if(!open)return;mounted.current=true;void load().catch(e=>setError(apiErrorMessage(e)));const t=setInterval(()=>{if(document.visibilityState==='visible')void load().catch(()=>{});},3000);return()=>clearInterval(t);},[open,load]);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');setNotice('');try{await fn();await load();}catch(e){setError(apiErrorMessage(e));}finally{if(mounted.current)setBusy(false);}};
 const exportNote=()=>{if(!data)return;const text=`# 회의실 ${roomId} 회의록\n\n${draft}\n\n## 할 일\n${data.tasks.map(t=>`- [${t.status==='DONE'?'x':' '}] ${t.title} · ${t.assignee||'미지정'} · ${t.dueDate||'기한 없음'}`).join('\n')}\n\n## 북마크\n${data.bookmarks.map(b=>`- ${Math.floor(b.atMs/60000)}분 ${b.label}`).join('\n')}`;const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`mingleroom-${roomId}-notes.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <Dialog open={open} onClose={()=>{if(!busy)onClose();}} fullWidth maxWidth="md" scroll="paper"><DialogTitle>회의 도구 <Chip size="small" label="자동 새로고침 3초" sx={{ml:1}}/></DialogTitle><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" allowScrollButtonsMobile><Tab label="회의록"/><Tab label="할 일"/><Tab label="투표"/><Tab label="북마크"/><Tab label="대화 검색"/></Tabs><DialogContent dividers sx={{minHeight:360}}>
 {busy&&<LinearProgress/>}{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{notice&&<Alert severity="success" sx={{mb:2}}>{notice}</Alert>}{!data?<Typography>회의 기록을 불러오는 중…</Typography>:<>
 {tab===0&&<Stack spacing={2}><Typography variant="body2" color="text.secondary">모든 참가자가 수정할 수 있어요. 저장 전 초안은 이 화면에 유지됩니다. 마지막 편집: {data.note.author||'없음'}</Typography>{dirty&&data.note.version!==version&&<Alert severity="warning">다른 참가자가 수정했어요. 내 초안을 복사한 후 최신 내용으로 교체하세요.</Alert>}<TextField label="공유 회의록" multiline minRows={10} value={draft} inputProps={{maxLength:50000}} onChange={e=>{setDraft(e.target.value);setDirty(true);}}/><Stack direction="row" spacing={1} flexWrap="wrap"><Button variant="contained" disabled={busy||!dirty} onClick={()=>void run(async()=>{const {data:n}=await apiClient.put<Note>(`${base}/note`,{content:draft,version});dirtyRef.current=false;setDirty(false);setVersion(n.version);setNotice('회의록을 저장했어요.');})}>회의록 저장</Button><Button disabled={busy} onClick={()=>{if(!dirty||window.confirm('현재 초안을 최신 저장 내용으로 교체할까요?')){setDraft(data.note.content);setVersion(data.note.version);setDirty(false);}}}>최신 내용으로 교체</Button><Button onClick={exportNote}>Markdown 내보내기</Button></Stack></Stack>}
 {tab===1&&<Stack spacing={2}>{elevated?<Box component="form" onSubmit={e=>{e.preventDefault();void run(async()=>{const body={...task,assigneeId:task.assigneeId?Number(task.assigneeId):null,dueDate:task.dueDate||null,revision:editing?.revision||0};if(editing)await apiClient.put(`${base}/tasks/${editing.id}`,body);else await apiClient.post(`${base}/tasks`,body);setTask(emptyTask);setEditing(null);});}}><Stack spacing={2}><TextField required label="할 일 제목" value={task.title} inputProps={{maxLength:200}} onChange={e=>setTask({...task,title:e.target.value})}/><TextField label="할 일 설명" multiline value={task.description} inputProps={{maxLength:10000}} onChange={e=>setTask({...task,description:e.target.value})}/><Stack direction={{xs:'column',sm:'row'}} spacing={1}><TextField select fullWidth label="담당자" value={task.assigneeId} onChange={e=>setTask({...task,assigneeId:e.target.value})}><MenuItem value="">미지정</MenuItem>{participants.map(p=><MenuItem key={p.id} value={p.id}>{p.name}</MenuItem>)}</TextField><TextField fullWidth label="기한" type="date" slotProps={{inputLabel:{shrink:true}}} value={task.dueDate} onChange={e=>setTask({...task,dueDate:e.target.value})}/><TextField select fullWidth label="상태" value={task.status} onChange={e=>setTask({...task,status:e.target.value as Task['status']})}>{(['TODO','DOING','DONE'] as const).map((s,i)=><MenuItem key={s} value={s}>{['할 일','진행 중','완료'][i]}</MenuItem>)}</TextField></Stack><Stack direction="row"><Button type="submit" variant="contained" disabled={busy||!task.title.trim()}>{editing?'할 일 수정 저장':'할 일 추가'}</Button>{editing&&<Button onClick={()=>{setEditing(null);setTask(emptyTask);}}>수정 취소</Button>}</Stack></Stack></Box>:<Alert severity="info">호스트와 발표자가 할 일을 관리합니다.</Alert>}{data.tasks.length===0&&<Typography>등록된 할 일이 없어요.</Typography>}{data.tasks.map(t=><Box key={t.id} sx={{border:'1px solid',borderColor:'divider',borderRadius:2,p:2}}><Chip size="small" label={{TODO:'할 일',DOING:'진행 중',DONE:'완료'}[t.status]}/><Typography fontWeight={700} sx={{mt:1}}>{t.title}</Typography><Typography sx={{whiteSpace:'pre-wrap'}}>{t.description}</Typography><Typography variant="body2" color="text.secondary">{t.assignee||'미지정'} · {t.dueDate||'기한 없음'}</Typography>{elevated&&<><Button disabled={busy} onClick={()=>{setEditing(t);setTask({title:t.title,description:t.description||'',assigneeId:t.assigneeId?String(t.assigneeId):'',dueDate:t.dueDate||'',status:t.status});}}>수정</Button><Button color="error" disabled={busy} onClick={()=>{if(window.confirm('이 할 일을 삭제할까요?'))void run(()=>apiClient.delete(`${base}/tasks/${t.id}?revision=${t.revision}`));}}>삭제</Button></>}</Box>)}</Stack>}
 {tab===2&&<Stack spacing={2}>{elevated&&<Box component="form" onSubmit={e=>{e.preventDefault();void run(async()=>{await apiClient.post(`${base}/polls`,{question,options:options.split('\n').map(v=>v.trim()).filter(Boolean)});setQuestion('');});}}><Stack spacing={2}><TextField label="투표 질문" required value={question} inputProps={{maxLength:255}} onChange={e=>setQuestion(e.target.value)}/><TextField label="선택지 (한 줄에 하나, 2~8개)" required multiline minRows={2} value={options} onChange={e=>setOptions(e.target.value)}/><Button type="submit" variant="contained" disabled={busy||!question.trim()}>투표 만들기</Button></Stack></Box>}<Typography variant="body2" color="text.secondary">참가자별 한 표 · 마감 전 변경 가능 · 결과에는 투표자 이름을 표시하지 않습니다. 서버에는 중복 방지를 위해 계정이 기록됩니다.</Typography>{data.polls.length===0&&<Typography>진행 중인 투표가 없어요.</Typography>}{data.polls.map(p=><Box key={p.id} sx={{p:2,border:'1px solid',borderColor:'divider',borderRadius:2}}><Typography fontWeight={700}>{p.question} {p.closed&&'· 마감'}</Typography><Stack spacing={1} sx={{mt:1}}>{p.options.map(o=><Button key={o.id} variant={p.myVote===o.id?'contained':'outlined'} disabled={busy||p.closed} onClick={()=>void run(()=>apiClient.put(`${base}/polls/${p.id}/vote`,{optionId:o.id}))}>{o.label} · {o.count}표 {p.myVote===o.id&&'✓'}</Button>)}</Stack>{elevated&&!p.closed&&<Button disabled={busy} onClick={()=>{if(window.confirm('투표를 마감할까요? 다시 열 수 없습니다.'))void run(()=>apiClient.post(`${base}/polls/${p.id}/close`));}}>투표 마감</Button>}</Box>)}</Stack>}
 {tab===4&&<ChatSearch roomId={roomId}/>}
 {tab===3&&<Stack spacing={2}><Typography variant="body2">회의실 생성 시점부터의 시간을 서버 기준으로 기록합니다.</Typography><Box component="form" onSubmit={e=>{e.preventDefault();void run(async()=>{await apiClient.post(`${base}/bookmarks`,{label});setLabel('');});}}><Stack direction="row" spacing={1}><TextField fullWidth label="북마크 메모" value={label} inputProps={{maxLength:120}} onChange={e=>setLabel(e.target.value)}/><Button type="submit" disabled={busy||!label.trim()}>기록</Button></Stack></Box>{data.bookmarks.map(b=><Box key={b.id}><Typography>{Math.floor(b.atMs/60000)}:{String(Math.floor(b.atMs/1000)%60).padStart(2,'0')} · {b.label}</Typography><Typography variant="caption">{b.author}</Typography>{(elevated||String(b.authorId)===me.id)&&<Button disabled={busy} color="error" onClick={()=>{if(window.confirm('북마크를 삭제할까요?'))void run(()=>apiClient.delete(`${base}/bookmarks/${b.id}`));}}>삭제</Button>}</Box>)}</Stack>}
 </>}
 </DialogContent><DialogActions><Button disabled={busy} onClick={onClose}>닫기</Button></DialogActions></Dialog>;
}
